### ISSUE TITLE
CRD registration for MySQL Cluster

### ISSUE THREAD

**Issue by earlgreyz** [grtl/mysql-operator#1]
Create `yaml` file to allow `MySQLCluster` CR registration via
```bash
> kubectl create -f mysql-cluster-crd.yaml
```
And provide function to register `MySQLCluster` via Go.

**Comment by earlgreyz** [comment]
https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/

**Comment by earlgreyz** [comment]
Yaml file should include validation on properties (example below):

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```
